const { chatJSON } = require("../services/openai.service");
const { QUESTION_GENERATION_SYSTEM, buildQuestionPrompt } = require("../prompts/interview.prompt");

const FALLBACK_QUESTIONS = {
  Normal: {
    Beginner: [
      "What does it mean to write clean code?",
      "Can you explain what a function is and why we use them?",
      "What is the difference between a bug and a feature?",
      "What does version control mean to you?",
      "Can you explain what an API is in simple terms?",
      "What is the difference between a compiler and an interpreter?",
      "What does it mean for code to be readable?",
      "Can you explain what a loop is and give an example of when you would use one?",
      "What is the difference between frontend and backend development?",
      "What does debugging mean to you?",
      "What is a variable and why do we use them in programming?",
      "Can you explain what a database is in simple terms?",
      "What is the difference between saving a file locally and in the cloud?",
      "What does it mean to test your code?",
      "Can you explain what open source software means?",
    ],
    Intermediate: [
      "How do you prioritize tasks when working under pressure?",
      "Describe a challenge you solved recently and how you approached it.",
      "How do you approach debugging a problem you have never seen before?",
      "What is one skill you are currently improving, and how are you working on it?",
      "How do you decide when code is good enough to ship?",
      "How do you handle a situation where requirements change mid-project?",
      "What is your approach to writing code that other developers can maintain?",
      "How do you stay up to date with new technologies in your field?",
      "Describe a time you had to refactor existing code and what drove that decision.",
      "How do you approach estimating how long a task will take?",
      "What is your process for reviewing someone else's code?",
      "How do you handle a situation where you disagree with a technical decision made by your team?",
      "Describe a time you had to work with incomplete or unclear requirements.",
      "How do you balance writing tests with delivering features quickly?",
      "What strategies do you use to avoid introducing bugs when making changes to existing code?",
    ],
    Advanced: [
      "How would you design a system that needs to handle 1 million requests per day?",
      "Describe a situation where you had to make a difficult architectural decision and its trade-offs.",
      "How do you approach technical debt in a fast-moving codebase?",
      "What strategies do you use to ensure reliability in a distributed system?",
      "How would you lead a team through a major refactor without breaking production?",
      "How would you design a CI/CD pipeline for a large team with multiple services?",
      "What is your approach to capacity planning for a growing system?",
      "How would you handle a production outage affecting thousands of users?",
      "Describe how you would migrate a monolith to microservices without downtime.",
      "How do you ensure security best practices are followed across a large engineering team?",
      "What is your approach to observability and monitoring in a distributed system?",
      "How would you design a feature flag system for gradual rollouts?",
      "Describe how you would architect a real-time notification system at scale.",
      "How do you approach performance optimization when you do not know where the bottleneck is?",
      "What is your strategy for ensuring backward compatibility when evolving an API?",
    ],
  },
  Java: {
    Beginner: [
      "What is the difference between a class and an object in Java?",
      "What does the static keyword mean in Java?",
      "Can you explain what inheritance is in Java?",
      "What is the difference between int and Integer in Java?",
      "What is a constructor and why do we use it?",
      "What is the difference between public, private, and protected in Java?",
      "What does the final keyword do in Java?",
      "Can you explain what a method is in Java?",
      "What is the difference between == and .equals() in Java?",
      "What is an array in Java and how do you declare one?",
      "What does it mean to override a method in Java?",
      "What is a package in Java and why is it useful?",
      "What is the difference between a String and a char in Java?",
      "What does null mean in Java?",
      "What is a loop in Java and what are the different types?",
    ],
    Intermediate: [
      "What is the difference between an interface and an abstract class in Java?",
      "How does Java handle exceptions, and when would you use checked vs unchecked exceptions?",
      "How does the Java Collections Framework work, and when would you use a HashMap vs a TreeMap?",
      "How would you implement thread safety in a Java application?",
      "What is the difference between ArrayList and LinkedList, and when would you choose each?",
      "How does the synchronized keyword work in Java?",
      "What is the difference between Comparable and Comparator in Java?",
      "How does Java's garbage collector decide what to collect?",
      "What is the purpose of the volatile keyword in Java?",
      "How would you use Java streams to process a large collection of data?",
      "What is the difference between HashMap and ConcurrentHashMap?",
      "How does dependency injection work in Spring?",
      "What is the difference between @Component, @Service, and @Repository in Spring?",
      "How would you handle database connection pooling in a Java application?",
      "What is the purpose of the Optional class in Java and when would you use it?",
    ],
    Advanced: [
      "How does Java memory management and garbage collection work at a deep level?",
      "How would you design a scalable Spring Boot microservice with proper fault tolerance?",
      "Explain the Java memory model and how it affects concurrent programming.",
      "How would you optimize a Java application experiencing high GC pressure?",
      "What are the trade-offs between virtual threads in Java 21 vs traditional thread pools?",
      "How would you implement a distributed lock in a Java microservices environment?",
      "What are the performance implications of using reflection in Java?",
      "How would you design a Java application to handle 100,000 concurrent connections?",
      "Explain how the JIT compiler optimizes Java bytecode at runtime.",
      "How would you diagnose and fix a memory leak in a production Java application?",
      "What are the trade-offs between using an ORM like Hibernate vs raw JDBC?",
      "How would you implement event sourcing in a Java application?",
      "What is the difference between optimistic and pessimistic locking in JPA?",
      "How would you design a Java service that needs to process millions of messages per hour?",
      "What are the implications of class loading in a large Java application and how would you manage it?",
    ],
  },
  Python: {
    Beginner: [
      "What is the difference between a list and a tuple in Python?",
      "What does it mean for Python to be dynamically typed?",
      "Can you explain what a dictionary is in Python?",
      "What is the difference between == and is in Python?",
      "What is a function in Python and how do you define one?",
      "What does the len() function do in Python?",
      "What is the difference between print() and return in Python?",
      "What is indentation and why does it matter in Python?",
      "What is a string in Python and how do you concatenate two strings?",
      "What does it mean to import a module in Python?",
      "What is the difference between a for loop and a while loop in Python?",
      "What is None in Python and when would you use it?",
      "What is a boolean in Python and what values can it have?",
      "How do you handle an error in Python using try and except?",
      "What is the difference between a local and a global variable in Python?",
    ],
    Intermediate: [
      "What are Python generators, and when would you use them over a list?",
      "What are decorators in Python, and can you give a practical use case?",
      "How does Python's GIL affect multi-threaded programs?",
      "How would you structure a Python backend service for maintainability?",
      "What is the difference between shallow copy and deep copy in Python?",
      "How does list comprehension work and when would you use it?",
      "What is the difference between *args and **kwargs in Python?",
      "How does Python's context manager work and when would you use the with statement?",
      "What is the difference between a module and a package in Python?",
      "How would you use Python's logging module in a production application?",
      "What is the purpose of __init__.py in a Python package?",
      "How does Python handle multiple inheritance and what is the MRO?",
      "What is the difference between threading and multiprocessing in Python?",
      "How would you write a unit test for a Python function using pytest?",
      "What is a virtual environment in Python and why should you use one?",
    ],
    Advanced: [
      "How does Python's memory management and reference counting work internally?",
      "How would you design a high-performance async Python service using asyncio?",
      "What are metaclasses in Python and when would you actually use one?",
      "How would you profile and optimize a slow Python application in production?",
      "Explain how Python's import system works and how you would structure a large package.",
      "How does the asyncio event loop work under the hood?",
      "What are the trade-offs between using multiprocessing, threading, and asyncio in Python?",
      "How would you implement a distributed task queue in Python?",
      "What are descriptors in Python and how do they work?",
      "How would you design a Python library that is both easy to use and highly extensible?",
      "What are the performance implications of using pandas for large datasets and how would you optimize it?",
      "How would you implement a custom context manager using both a class and a generator?",
      "What is the difference between __getattr__ and __getattribute__ in Python?",
      "How would you build a plugin system in Python?",
      "What are the trade-offs of using Cython or ctypes to speed up Python code?",
    ],
  },
  JavaScript: {
    Beginner: [
      "What is the difference between let, const, and var in JavaScript?",
      "What is a callback function in JavaScript?",
      "Can you explain what the DOM is?",
      "What does undefined mean in JavaScript?",
      "What is the difference between == and === in JavaScript?",
      "What is an array in JavaScript and how do you add an item to it?",
      "What does typeof do in JavaScript?",
      "What is a function declaration vs a function expression in JavaScript?",
      "What does console.log() do and when would you use it?",
      "What is the difference between null and undefined in JavaScript?",
      "What is an object in JavaScript and how do you access its properties?",
      "What does the if/else statement do in JavaScript?",
      "What is a string template literal in JavaScript?",
      "What does the map() method do on an array?",
      "What is the difference between innerHTML and textContent?",
    ],
    Intermediate: [
      "What is the difference between synchronous and asynchronous JavaScript?",
      "Explain closures in JavaScript with a practical example.",
      "How does the event loop work in Node.js?",
      "What is event bubbling and how would you stop it?",
      "How do Promises differ from async/await, and when would you use each?",
      "What is the difference between call, apply, and bind in JavaScript?",
      "How does prototypal inheritance work in JavaScript?",
      "What is the difference between localStorage and sessionStorage?",
      "How does debouncing work and when would you use it?",
      "What is the difference between a shallow copy and a deep copy of an object in JavaScript?",
      "How does the this keyword behave differently in arrow functions vs regular functions?",
      "What is a JavaScript module and how does import/export work?",
      "How would you handle errors in an async/await function?",
      "What is the difference between forEach and map in JavaScript?",
      "How does the fetch API work and how would you handle a failed request?",
    ],
    Advanced: [
      "How would you optimize the performance of a large React application?",
      "Explain how JavaScript's prototype chain works and how it relates to class inheritance.",
      "How would you design a state management solution for a complex React app without Redux?",
      "What are the memory leak patterns in JavaScript and how do you detect them?",
      "How does V8 optimize JavaScript execution, and what patterns should you avoid?",
      "How does React's reconciliation algorithm work?",
      "What are the trade-offs between server-side rendering and client-side rendering in Next.js?",
      "How would you implement a virtual scroll list for rendering 100,000 items efficiently?",
      "What is the difference between microtasks and macrotasks in the JavaScript event loop?",
      "How would you design a real-time collaborative editing feature in a web app?",
      "What are Web Workers and when would you use them?",
      "How would you implement code splitting and lazy loading in a React application?",
      "What are the security implications of using eval() in JavaScript?",
      "How does tree shaking work in a modern JavaScript bundler?",
      "How would you architect a large-scale frontend application for a team of 20 developers?",
    ],
  },
  "C++": {
    Beginner: [
      "What is the difference between a pointer and a reference in C++?",
      "What does const mean when applied to a variable in C++?",
      "Can you explain what a class is in C++?",
      "What is the difference between stack and heap memory?",
      "What is a constructor and when is it called?",
      "What is the difference between struct and class in C++?",
      "What does the new keyword do in C++?",
      "What is a destructor and why is it important?",
      "What is the difference between pass by value and pass by reference in C++?",
      "What does include do at the top of a C++ file?",
      "What is a namespace in C++ and why is it useful?",
      "What is the difference between int and long in C++?",
      "What does the return statement do in a C++ function?",
      "What is an array in C++ and how do you declare one?",
      "What is the difference between while and do-while loops in C++?",
    ],
    Intermediate: [
      "When would you use virtual functions in C++, and what is the vtable?",
      "What is RAII and why is it important in C++?",
      "How do smart pointers work and when would you use unique_ptr vs shared_ptr?",
      "What is the difference between deep copy and shallow copy in C++?",
      "How does template specialization work in C++?",
      "What is the difference between stack unwinding and exception handling in C++?",
      "How does the STL vector manage memory internally?",
      "What is the difference between a map and an unordered_map in C++?",
      "How does move semantics improve performance in C++?",
      "What is the rule of three and when does it apply?",
      "How does operator overloading work in C++?",
      "What is the difference between static and dynamic polymorphism in C++?",
      "How would you implement a thread-safe singleton in C++?",
      "What is the purpose of the explicit keyword in C++?",
      "How does const correctness improve code quality in C++?",
    ],
    Advanced: [
      "How does the C++ memory model affect concurrent programming?",
      "What are the performance implications of virtual dispatch and how would you avoid it?",
      "How would you design a lock-free data structure in C++?",
      "Explain move semantics and perfect forwarding in C++11 and beyond.",
      "How would you profile and optimize a C++ application with high cache miss rates?",
      "What are the trade-offs between using std::thread and a thread pool in C++?",
      "How does template metaprogramming work and when would you use it?",
      "What are the implications of undefined behavior in C++ and how do you avoid it?",
      "How would you implement a custom memory allocator in C++?",
      "What is the difference between std::atomic and using a mutex for synchronization?",
      "How does the C++ linker work and what are common linking errors?",
      "What are the performance trade-offs between inheritance and composition in C++?",
      "How would you design a plugin system in C++ using dynamic loading?",
      "What are the implications of using exceptions vs error codes in a performance-critical C++ system?",
      "How does CRTP work and what problems does it solve?",
    ],
  },
  SQL: {
    Beginner: [
      "What is the difference between a primary key and a foreign key?",
      "What does a SELECT statement do in SQL?",
      "Can you explain what a JOIN is in simple terms?",
      "What is the difference between WHERE and HAVING in SQL?",
      "What does NULL mean in a database?",
      "What is the difference between DELETE and DROP in SQL?",
      "What does the ORDER BY clause do in SQL?",
      "What is a table in a relational database?",
      "What does INSERT INTO do in SQL?",
      "What is the difference between a row and a column in a database table?",
      "What does the COUNT() function do in SQL?",
      "What is an alias in SQL and how do you use it?",
      "What does DISTINCT do in a SQL query?",
      "What is the difference between AND and OR in a SQL WHERE clause?",
      "What does the UPDATE statement do in SQL?",
    ],
    Intermediate: [
      "What is the difference between INNER JOIN and LEFT JOIN?",
      "How do indexes improve query performance, and when would you add one?",
      "What are database transactions and why are they important?",
      "What is normalization and what problem does it solve?",
      "How would you write a query to find duplicate records in a table?",
      "What is the difference between a subquery and a JOIN?",
      "How does GROUP BY work and when would you use it?",
      "What is a view in SQL and when would you use one?",
      "What is the difference between UNION and UNION ALL?",
      "How would you write a query to find the second highest salary in a table?",
      "What is a stored procedure and when would you use one?",
      "What is the difference between CHAR and VARCHAR in SQL?",
      "How does a foreign key constraint enforce referential integrity?",
      "What is a self join and when would you use it?",
      "How would you use a window function like ROW_NUMBER() in a query?",
    ],
    Advanced: [
      "How would you optimize a slow SQL query on a table with 100 million rows?",
      "What are the trade-offs between normalized and denormalized database schemas?",
      "How do database locks work and how would you diagnose a deadlock?",
      "Explain the difference between clustered and non-clustered indexes and when to use each.",
      "How would you design a database schema for a multi-tenant SaaS application?",
      "What is query execution plan and how would you use it to optimize a query?",
      "How does MVCC work in PostgreSQL and why does it matter?",
      "What are the trade-offs between using a relational database and a NoSQL database?",
      "How would you implement pagination efficiently on a table with 50 million rows?",
      "What is database sharding and what problems does it introduce?",
      "How would you design a schema to support soft deletes without impacting query performance?",
      "What are the implications of using cascading deletes in a large relational database?",
      "How would you handle schema migrations in a production database with zero downtime?",
      "What is the difference between optimistic and pessimistic locking in SQL?",
      "How would you design an audit log table that tracks all changes to a critical table?",
    ],
  },
  HR: {
    Beginner: [
      "Tell me about yourself and what you are looking for in a role.",
      "What are your top three strengths?",
      "Why did you choose this field or career path?",
      "How do you handle feedback from a manager or peer?",
      "Describe a time you worked as part of a team.",
      "What motivates you to do your best work?",
      "How do you manage your time when you have multiple tasks to complete?",
      "What do you do when you do not understand something at work or school?",
      "Describe a time you helped a teammate with something.",
      "What is one thing you would like to improve about yourself professionally?",
      "How do you prepare for an important task or presentation?",
      "What does a good work environment look like to you?",
      "Describe a time you made a mistake and what you did about it.",
      "What are your short-term career goals?",
      "How do you stay organized when managing multiple responsibilities?",
    ],
    Intermediate: [
      "Describe a challenge you faced at work or school and how you resolved it.",
      "How do you handle disagreements with teammates?",
      "Tell me about a time you had to learn something new quickly.",
      "How do you manage your time when handling multiple responsibilities?",
      "Describe a situation where you showed initiative without being asked.",
      "Tell me about a time you received critical feedback and how you responded.",
      "How do you handle working with someone whose communication style is very different from yours?",
      "Describe a time you had to meet a tight deadline and how you managed it.",
      "Tell me about a project you are proud of and what your specific contribution was.",
      "How do you approach a situation where you have to say no to a request?",
      "Describe a time you had to adapt quickly to an unexpected change.",
      "How do you build trust with a new team or manager?",
      "Tell me about a time you went above and beyond what was expected of you.",
      "How do you handle a situation where you are blocked and cannot make progress?",
      "Describe a time you had to balance quality with speed and how you made that trade-off.",
    ],
    Advanced: [
      "Tell me about a time you led a project or team through a difficult situation.",
      "Describe a situation where you had to influence stakeholders without direct authority.",
      "How have you handled a situation where you disagreed with a senior decision?",
      "Tell me about a time you had to deliver difficult feedback to a colleague.",
      "Describe a situation where you had to make a high-stakes decision with incomplete information.",
      "How have you built and maintained a high-performing team?",
      "Tell me about a time you had to manage conflict between two team members.",
      "Describe a situation where you had to drive organizational change and faced resistance.",
      "How do you approach setting goals and holding yourself and your team accountable?",
      "Tell me about a time you had to recover a project that was significantly behind schedule.",
      "How do you create an environment where team members feel safe to take risks and fail?",
      "Describe a time you had to make a decision that was unpopular but necessary.",
      "How do you identify and develop talent on your team?",
      "Tell me about a time you had to manage competing priorities from multiple stakeholders.",
      "How do you ensure your team stays aligned and motivated during periods of uncertainty?",
    ],
  },
  "Resume-Based": {
    Beginner: [
      "Can you walk me through your resume in two to three minutes?",
      "What is the project on your resume you are most comfortable explaining?",
      "Which skill on your resume did you learn most recently?",
      "Tell me about your educational background and how it relates to this role.",
      "What tools or technologies on your resume do you use most often?",
      "Which item on your resume are you most proud of and why?",
      "What was your role in the first project listed on your resume?",
      "Is there anything on your resume you would like to explain in more detail?",
      "What motivated you to learn the first skill listed on your resume?",
      "How long have you been working with the main technology on your resume?",
      "What is one thing you learned from your most recent experience on your resume?",
      "Which project on your resume took the longest to complete?",
      "What was the team size for the main project on your resume?",
      "What tools did you use to build the first project on your resume?",
      "What would you say is the main theme or focus of your resume?",
    ],
    Intermediate: [
      "Walk me through the most impactful project on your resume.",
      "Which skill on your resume are you most confident in, and why?",
      "Tell me about a result on your resume that you are especially proud of.",
      "Describe a challenge you faced in one of the projects listed on your resume.",
      "How did you measure the success of a project on your resume?",
      "What trade-offs did you make in one of the projects on your resume?",
      "How did you collaborate with others in the experience listed on your resume?",
      "What would you do differently if you could redo one of the projects on your resume?",
      "How did the skills on your resume prepare you for this role?",
      "Describe a technical decision you made in one of your resume projects and why you made it.",
      "What was the biggest lesson you learned from your most recent role on your resume?",
      "How did you handle a disagreement or conflict in one of the teams on your resume?",
      "What impact did your work have on the users or business in one of your resume projects?",
      "How did you grow technically during the experience listed on your resume?",
      "What is the most complex problem you solved in any project on your resume?",
    ],
    Advanced: [
      "Which project on your resume best demonstrates your ability to solve a complex technical problem?",
      "Tell me about a time on your resume where you had to make a difficult architectural or design decision.",
      "What is the most technically challenging thing you have built, and what were the trade-offs?",
      "Describe a situation from your resume where you had to balance speed and quality under pressure.",
      "If you could redo one project on your resume, what would you change and why?",
      "How did you ensure scalability and reliability in the most complex project on your resume?",
      "Describe a time from your resume where you had to lead a technical initiative from start to finish.",
      "What was the most significant performance optimization you made in any project on your resume?",
      "How did you handle technical debt in one of the projects on your resume?",
      "Describe a situation from your resume where you had to mentor or guide a less experienced teammate.",
      "What was the most impactful architectural decision you made in any project on your resume?",
      "How did you approach testing and quality assurance in your most complex resume project?",
      "Describe a time from your resume where a project did not go as planned and how you recovered.",
      "What is the most innovative solution you built in any project on your resume?",
      "How did you ensure security and data integrity in the most critical project on your resume?",
    ],
  },
};

const isNonAnswer = (answer = "") => {
  const lower = String(answer).toLowerCase().trim();
  return (
    lower.length <= 20 &&
    /\b(i don't know|i dont know|don't know|dont know|do not know|not sure|no idea|can't remember|cannot remember|sorry)\b/.test(lower)
  );
};

const getFallbackQuestion = ({ track, difficulty = "Intermediate", previousQuestions = [], lastAnswer }) => {
  const trackBank = FALLBACK_QUESTIONS[track] || FALLBACK_QUESTIONS.Normal;
  const pool = trackBank[difficulty] || trackBank.Intermediate || Object.values(trackBank)[0];
  const unused = pool.filter((q) => !previousQuestions.includes(q));
  if (isNonAnswer(lastAnswer)) return (unused[0] || pool[0]).trim();
  return (unused[0] || pool[previousQuestions.length % pool.length]).trim();
};

const generateQuestion = async ({
  track,
  difficulty,
  previousQuestions = [],
  conversationHistory = [],
  lastQuestion,
  lastAnswer,
  resumeContext,
}) => {
  let result;
  try {
    result = await chatJSON(
      QUESTION_GENERATION_SYSTEM,
      buildQuestionPrompt({ track, difficulty, previousQuestions, conversationHistory, lastQuestion, lastAnswer, resumeContext }),
      undefined,
      0.9
    );
  } catch {
    return getFallbackQuestion({ track, difficulty, previousQuestions, lastAnswer });
  }

  if (!result?.question || typeof result.question !== "string") {
    return getFallbackQuestion({ track, difficulty, previousQuestions, lastAnswer });
  }

  const question = result.question.trim();

  if (previousQuestions.some(q => q.toLowerCase().trim() === question.toLowerCase().trim())) {
    return getFallbackQuestion({ track, difficulty, previousQuestions });
  }

  return question;
};

module.exports = { generateQuestion };
